libdigidocpp: digidoc::XmlConfV2 Class Reference
digidoc::XmlConfV2 Class Reference
Version 2 of XML Configuration class.
#include <XmlConf.h>
Inherits digidoc::ConfV2.
Public Member Functions
XmlConfV2 (const std::string &path="", const std::string &schema="")
virtual ~XmlConfV2 ()
virtual int logLevel () const override
virtual std::string logFile () const override
virtual std::string PKCS11Driver () const override
virtual std::string proxyHost () const override
virtual std::string proxyPort () const override
virtual std::string proxyUser () const override
virtual std::string proxyPass () const override
virtual bool proxyForceSSL () const override
virtual bool proxyTunnelSSL () const override
virtual std::string digestUri () const override
virtual std::string signatureDigestUri () const override
virtual std::string ocsp (const std::string &issuer) const override
virtual std::string TSUrl () const override
virtual X509Cert verifyServiceCert () const override
virtual std::string verifyServiceUri () const override
virtual std::string PKCS12Cert () const override
virtual std::string PKCS12Pass () const override
virtual bool PKCS12Disable () const override
virtual bool TSLAutoUpdate () const override
virtual std::string TSLCache () const override
virtual bool TSLOnlineDigest () const override
virtual int TSLTimeOut () const override
virtual void setProxyHost (const std::string &host)
virtual void setProxyPort (const std::string &port)
virtual void setProxyUser (const std::string &user)
virtual void setProxyPass (const std::string &pass)
virtual void setProxyTunnelSSL (bool enable)
virtual void setPKCS12Cert (const std::string &cert)
virtual void setPKCS12Pass (const std::string &pass)
virtual void setPKCS12Disable (bool disable)
virtual void setTSLOnlineDigest (bool enable)
virtual void setTSLTimeOut (int timeOut)
Public Member Functions inherited from digidoc::ConfV2
ConfV2 ()
virtual ~ConfV2 ()
Public Member Functions inherited from digidoc::Conf
Conf ()
virtual ~Conf ()
virtual DEPRECATED_DIGIDOCPP std::string libdigidocConf () const
virtual DEPRECATED_DIGIDOCPP std::string certsPath () const
virtual std::string xsdPath () const
virtual bool TSLAllowExpired () const
virtual std::vector< X509Cert > TSLCerts () const
virtual std::string TSLUrl () const
Additional Inherited Members
Static Public Member Functions inherited from digidoc::ConfV2
static ConfV2 * instance ()
Static Public Member Functions inherited from digidoc::Conf
static void init (Conf *conf)
static Conf * instance ()
Detailed Description
Version 2 of XML Configuration class.
See also
digidoc::ConfV2
Constructor & Destructor Documentation
XmlConfV2::XmlConfV2 (const std::string & path = "", const std::string & schema = "") explicit
Initialize xml conf from path
XmlConfV2::~XmlConfV2 () virtual
References digestUri(), logFile(), logLevel(), PKCS11Driver(), PKCS12Cert(), PKCS12Disable(), PKCS12Pass(), proxyForceSSL(), proxyHost(), proxyPass(), proxyPort(), proxyTunnelSSL(), proxyUser(), signatureDigestUri(), TSLAutoUpdate(), TSLCache(), TSLOnlineDigest(), TSLTimeOut(), TSUrl(), and verifyServiceUri().
Member Function Documentation
virtual std::string digidoc::XmlConfV2::digestUri () const override virtual
Return default digest type as URI
Reimplemented from digidoc::Conf.
Referenced by ~XmlConfV2().
virtual std::string digidoc::XmlConfV2::logFile () const override virtual
Gets log file location. Default log goes to standard out stream
Reimplemented from digidoc::Conf.
Referenced by ~XmlConfV2().
virtual int digidoc::XmlConfV2::logLevel () const override virtual
Returns log level. 0 = Error 1 = Warn 2 = Info 3 = Debug
Reimplemented from digidoc::Conf.
Referenced by ~XmlConfV2().
string XmlConfV2::ocsp (const std::string & issuer) const override virtual
Return OCSP request URL
Parameters
issuer OCSP issuer.
Reimplemented from digidoc::Conf.
References digidoc::Conf::ocsp(), PKCS12Cert(), PKCS12Disable(), PKCS12Pass(), proxyHost(), proxyPass(), proxyPort(), proxyTunnelSSL(), proxyUser(), setPKCS12Cert(), setPKCS12Disable(), setPKCS12Pass(), setProxyHost(), setProxyPass(), setProxyPort(), setProxyTunnelSSL(), setProxyUser(), setTSLOnlineDigest(), setTSLTimeOut(), TSLOnlineDigest(), and TSLTimeOut().
virtual std::string digidoc::XmlConfV2::PKCS11Driver () const override virtual
Returns PKCS11 driver file path
Reimplemented from digidoc::Conf.
Referenced by ~XmlConfV2().
virtual std::string digidoc::XmlConfV2::PKCS12Cert () const override virtual
Gets PKCS12 certificate file location.
Used for signing OCSP request
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConfV2().
virtual bool digidoc::XmlConfV2::PKCS12Disable () const override virtual
Gets PKCS12 usage.
See also
digidoc::Conf::PKCS12Cert
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConfV2().
virtual std::string digidoc::XmlConfV2::PKCS12Pass () const override virtual
Gets PKCS12 password.
See also
digidoc::Conf::PKCS12Cert
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConfV2().
virtual bool digidoc::XmlConfV2::proxyForceSSL () const override virtual
Redirect SSL traffic over proxy server Default: false
Reimplemented from digidoc::Conf.
Referenced by ~XmlConfV2().
virtual std::string digidoc::XmlConfV2::proxyHost () const override virtual
Gets proxy host address.
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConfV2().
virtual std::string digidoc::XmlConfV2::proxyPass () const override virtual
Gets proxy login password.
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConfV2().
virtual std::string digidoc::XmlConfV2::proxyPort () const override virtual
Gets proxy port number.
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConfV2().
virtual bool digidoc::XmlConfV2::proxyTunnelSSL () const override virtual
Tunnel SSL traffic over proxy server Default: false
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConfV2().
virtual std::string digidoc::XmlConfV2::proxyUser () const override virtual
Gets proxy user name.
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConfV2().
virtual void digidoc::XmlConfV2::setPKCS12Cert (const std::string & cert) virtual
Referenced by ocsp().
virtual void digidoc::XmlConfV2::setPKCS12Disable (bool disable) virtual
Referenced by ocsp().
virtual void digidoc::XmlConfV2::setPKCS12Pass (const std::string & pass) virtual
Referenced by ocsp().
virtual void digidoc::XmlConfV2::setProxyHost (const std::string & host) virtual
Referenced by ocsp().
virtual void digidoc::XmlConfV2::setProxyPass (const std::string & pass) virtual
Referenced by ocsp().
virtual void digidoc::XmlConfV2::setProxyPort (const std::string & port) virtual
Referenced by ocsp().
virtual void digidoc::XmlConfV2::setProxyTunnelSSL (bool enable) virtual
Referenced by ocsp().
virtual void digidoc::XmlConfV2::setProxyUser (const std::string & user) virtual
Referenced by ocsp().
virtual void digidoc::XmlConfV2::setTSLOnlineDigest (bool enable) virtual
Referenced by ocsp().
virtual void digidoc::XmlConfV2::setTSLTimeOut (int timeOut) virtual
Referenced by ocsp().
virtual std::string digidoc::XmlConfV2::signatureDigestUri () const override virtual
Gets signature digest URI
Reimplemented from digidoc::Conf.
Referenced by ~XmlConfV2().
virtual bool digidoc::XmlConfV2::TSLAutoUpdate () const override virtual
Download new TSL list when it is expired or invalid
Reimplemented from digidoc::Conf.
Referenced by ~XmlConfV2().
virtual std::string digidoc::XmlConfV2::TSLCache () const override virtual
TSL cache path in local file system
Reimplemented from digidoc::Conf.
Referenced by ~XmlConfV2().
virtual bool digidoc::XmlConfV2::TSLOnlineDigest () const override virtual
Compare local TSL digest with digest published online to check for newer version
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConfV2().
virtual int digidoc::XmlConfV2::TSLTimeOut () const override virtual
Gets TSL downloading connection's current timeout value
Reimplemented from digidoc::Conf.
Referenced by ocsp(), and ~XmlConfV2().
virtual std::string digidoc::XmlConfV2::TSUrl () const override virtual
Returns default time-stamp server URL
Reimplemented from digidoc::Conf.
Referenced by ~XmlConfV2().
X509Cert XmlConfV2::verifyServiceCert () const override virtual
Enables SSL proxy connections
Exceptions
Exception exception is thrown if saving into a user configuration file fails.
Reimplemented from digidoc::ConfV2.
References digidoc::ConfV2::verifyServiceCert().
virtual std::string digidoc::XmlConfV2::verifyServiceUri () const override virtual
Gets verify service URI
Reimplemented from digidoc::Conf.
Referenced by ~XmlConfV2().
The documentation for this class was generated from the following files:
XmlConf.h
XmlConf.cpp